---
title: Ex-3-5350
date: 2025-03-20
author: Your Name
cell_count: 7
score: 5
---

```python
#created at 20250311
```


```python
#https://stevejoe1412.gitbook.io/ssn/python-subtopics/4.-descriptor-protocols
```


```python
#Descriptor with validation
```


```python
class PositiveNumber:
    def __get__(self,instance,owner):
        return istance._value

    def __set__(self,instance,value):
        if value < 0:
            raise ValueError("Number must be positive")
        instnace._value = value
        
```


```python
class MyClass:
    number = PositiveNumber()
```


```python
obj = MyClass()
obj.number = 10
print( obj.number)
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    Cell In[9], line 2
          1 obj = MyClass()
    ----> 2 obj.number = 10
          3 print( obj.number)


    Cell In[7], line 8, in PositiveNumber.__set__(self, instance, value)
          6 if value < 0:
          7     raise ValueError("Number must be positive")
    ----> 8 instnace._value = value


    NameError: name 'instnace' is not defined



```python

```


---
**Score: 5**