---
title: Ex-6-5869
date: 2025-04-29
author: Your Name
cell_count: 7
score: 5
---

```python
#created at 20250311
```


```python
#https://stevejoe1412.gitbook.io/ssn/python-subtopics/4.-descriptor-protocols
```


```python
#combining __get__ and __set__
```


```python
class Descriptor:
    def __get__(self,instance,owner):
        return instance.__dict__.get("_value",None)

    def __set__(self,instance,value):
        print(f"setting value to{value}")
        instance.__dict__["_value"] = value
```


```python
class MyClass:
    attribute = Descriptor()
```


```python
obj = MyClass()
obj.attribute = "hello"
print(obj.MyClass)
```

    setting value tohello



    ---------------------------------------------------------------------------

    AttributeError                            Traceback (most recent call last)

    Cell In[7], line 3
          1 obj = MyClass()
          2 obj.attribute = "hello"
    ----> 3 print(obj.MyClass)


    AttributeError: 'MyClass' object has no attribute 'MyClass'



```python

```


---
**Score: 5**