---
title: Ex-9-2177
date: 2025-04-21
author: Your Name
cell_count: 8
score: 5
---

```python
#created at 20250403
```


```python
#Basic Exception Handling
```


```python
print("\n === Basic Exception Handling ===")
```

    
     === Basic Exception Handling ===



```python
def divide_numbers(a, b):
    try:
        result =  a/b
        print(f"result:{result}")
    except ZerodivisionError:
        print("Error : Divison by zero")
    except TypeError:
        print("Error : Invalid Number Type !")
```


```python
divide_numbers(10, 2)
```

    result:5.0



```python
divide_numbers(2,0)
```


    ---------------------------------------------------------------------------

    ZeroDivisionError                         Traceback (most recent call last)

    Cell In[2], line 3, in divide_numbers(a, b)
          2 try:
    ----> 3     result =  a/b
          4     print(f"result:{result}")


    ZeroDivisionError: division by zero

    
    During handling of the above exception, another exception occurred:


    NameError                                 Traceback (most recent call last)

    Cell In[4], line 1
    ----> 1 divide_numbers(2,0)


    Cell In[2], line 5, in divide_numbers(a, b)
          3     result =  a/b
          4     print(f"result:{result}")
    ----> 5 except ZerodivisionError:
          6     print("Error : Divison by zero")
          7 except TypeError:


    NameError: name 'ZerodivisionError' is not defined



```python
divide_numbers('3', 1)
```


    ---------------------------------------------------------------------------

    TypeError                                 Traceback (most recent call last)

    Cell In[2], line 3, in divide_numbers(a, b)
          2 try:
    ----> 3     result =  a/b
          4     print(f"result:{result}")


    TypeError: unsupported operand type(s) for /: 'str' and 'int'

    
    During handling of the above exception, another exception occurred:


    NameError                                 Traceback (most recent call last)

    Cell In[5], line 1
    ----> 1 divide_numbers('3', 1)


    Cell In[2], line 5, in divide_numbers(a, b)
          3     result =  a/b
          4     print(f"result:{result}")
    ----> 5 except ZerodivisionError:
          6     print("Error : Divison by zero")
          7 except TypeError:


    NameError: name 'ZerodivisionError' is not defined



```python

```


---
**Score: 5**