---
title: Ex-16-1919
date: 2025-04-26
author: Your Name
cell_count: 7
score: 5
---

```python
#created at 20250415
```


```python
#Private Methods 
```


```python
print("\n === Private Methods === ")
```

    
     === Private Methods === 



```python
class processor:
    def __init__(self, data):
        self.data = data

    def process(self):
        processed_data = self.__clean_data()
        return self.__format_data(processed_data)

    def __clean_data(Self):
        return self.data.strip()

    def __format_data(self, data):
        return data.upper()
                
```


```python
proc = processor("Heloo World ")
```


```python
print(f"processed :{proc.process()}")
```


    ---------------------------------------------------------------------------

    NameError                                 Traceback (most recent call last)

    Cell In[5], line 1
    ----> 1 print(f"processed :{proc.process()}")


    Cell In[2], line 6, in processor.process(self)
          5 def process(self):
    ----> 6     processed_data = self.__clean_data()
          7     return self.__format_data(processed_data)


    Cell In[2], line 10, in processor.__clean_data(Self)
          9 def __clean_data(Self):
    ---> 10     return self.data.strip()


    NameError: name 'self' is not defined



```python

```


---
**Score: 5**